---
title: March 7, 2017 In-Class Project
date: '2017-03-07'
slug: march-7-2017-in-class-project
---



# Part 1: Cleaning up Your Website

Many of you have noticed that within your website there are many sections that you are not using at the moment. Most of you have sections called:

- Selected Publications
- Recent Publications
- Recent and Upcoming Talks
- Recent Posts
- Projects
- Teaching


We can begin to remove or rename these as you desire. Go into your website project:

~/contents/home/

In here are all of the pages that show up on your main website. Remove any of these documents that do not pertain to what you want on your site. Also you can rename them as well. So where it says teaching, you can leave this named `teaching.md` but inside this file you may want to rename this: "Relevant Courses". 

Once you do this, push your website to github. 

Here is a listing of all the class websites:

- [Allison](https://allisonstats.github.io)
- [Chang](https://vicchen1991.github.io)
- [Molly](https://MollyMcCarthy.github.io)
- [Patrick](https://zhangpa.github.io)
- [Tin](https://tinoreskovic.github.io)
- [Wanting](https://Wanting-Zhai.github.io)
- [Zheng](https://zsi1.github.io)



# Part 2: Jackknife Function


Now that you have cleaned up your site some more. Please click on the following in order to get to your repository for the lab. You will be asked to place yourselves in groups and then as a group you will have starter code to work on. 

[In Class Project](https://classroom.github.com/group-assignment-invitations/d0671ebf628d55e8adccd5c00aa77128)



