---
title: March 21, 2017 In Class Lab
date: '2017-03-21'
slug: in-class-lab
---



# Simulations in R


In your pre-class work you have created a simulation of a game.

There will be 2 parts to this class: 
  
1. Peer Review Pre-Class Simulations
2. Create New simulation in groups. 




## Peer Review

1. In this part, take the pre-class lab that you have created before. Add a fork of it into your personal github. 


2. Once the fork is there go into the github account below that you are being asked to review. Find their simulation and run through the code of this. 

3. Go into the issues tab on their github repository and make comments and suggestions. Comment on:
    a. Clarity
    b. Comments
    c. How well it runs. 

  

| Your Name | Github Name to Review |
| --------- | ---------------------- |
| Chang | tinoreskovic |
| Molly | vicchen1991 | 
| Tin | wanting-zhai | 
| Zheng | mollymccarthy | 
|Wanting | zhangpa | 
| Patrick | zsi1 | 


## Simulations in Class

[Simulations in Class](https://classroom.github.com/group-assignment-invitations/e247cedcbf5c310a34e4c41d10bd054b)